---
- name: Configure extra options for cron daemon
  hosts: icescrum-app-dc2-01.forge.prx.prod.dwadm.in
  gather_facts: true
  become: true
  vars:
    crond_extra_options: "-n"
  roles:
    - ansible-role-cron-service
  tags: ['crond']
